export const TRACKS = Object.freeze([
  { id: 'love', title: 'Love', subtitle: 'Een warm moment voor jezelf.', frequency: '528 Hz', label: 'LOVE FREQUENCY', color: '#4b918f', wash: '#e0edeb', image: 'assets/fork-original.jpg', playback: 'assets/fork-loop.wav', duration: 38.3679791667, sourceUrl: 'https://www.youtube.com/shorts/4ieSiVPC2M8', available: true },
  { id: 'sleep', title: 'Slaap', subtitle: 'Neem de tijd om af te schakelen.', frequency: 'Delta · 3 Hz', label: 'RUST & SLAPEN', color: '#7779a8', wash: '#e9e9f0', image: 'assets/fork-sleep.webp', playback: 'assets/sleep-loop.wav', duration: 32.5621995465, sourceUrl: 'https://www.youtube.com/shorts/AnQIT-jY9EU', available: true },
  { id: 'energy', title: 'Energie', subtitle: 'Een klank voor een nieuw begin.', frequency: 'Bèta · 15 Hz', label: 'EEN NIEUW MOMENT', color: '#b38c49', wash: '#f2ebdc', image: 'assets/fork-energy.webp', playback: 'assets/energy-loop.wav', duration: 39.4173242630, sourceUrl: 'https://www.youtube.com/shorts/Cq_PdOw-Kf8', available: true },
  { id: 'focus', title: 'Focus', subtitle: 'Ruimte voor één ding tegelijk.', frequency: 'Alfa · 10 Hz', label: 'AANDACHT & RUIMTE', color: '#638d77', wash: '#e4ece4', image: 'assets/fork-focus.webp', playback: 'assets/focus-loop.wav', duration: 33.3952380952, sourceUrl: 'https://www.youtube.com/shorts/ENzNJjju7NI', available: true },
  { id: 'meditate', title: 'Meditatie', subtitle: 'Even niets hoeven. Alleen luisteren.', frequency: 'Thèta · 6 Hz', label: 'EEN MOMENT STILTE', color: '#9a7b9b', wash: '#eee5ee', image: 'assets/fork-meditate.webp', playback: 'assets/meditate-loop.wav', duration: 32.1241723356, sourceUrl: 'https://www.youtube.com/shorts/B-ldA8ggKeM', available: true }
].map(track => Object.freeze(track)));

export const SOURCE_NOTE = 'Sound Healing Vibes. Bij delta, bèta, alfa en thèta noemt de maker de binaurale verschilfrequentie. Luister hiervoor in stereo met een koptelefoon. De themanamen beloven geen effect.';
